language: cpp

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      dist: trusty
      sudo: required
      xdist: ubuntu
    - os: osx
      osx_image: xcode7.3
      xdist: osx

env:
  ###
  ### Ubuntu 14.04
  ###
  ### Ubuntu 14.04 x86_64, Qt 5.5 - DO NOT DEPLOY
  - xdist: ubuntu
    xdistver: "14.04"
    init: /sbin/init
    qtenv: /opt/qt55/bin/qt55-env.sh
    qtpkg: "'qt55base qt55quickcontrols qt55svg mesa-common-dev libgl1-mesa-dev'"
    qtppa: ppa:beineri/opt-qt551-trusty
  ### Ubuntu 14.04 x86_64, Qt 5.6 - DEPLOY
  - xdist: ubuntu
    xdistver: "14.04"
    init: /sbin/init
    qtenv: /opt/qt56/bin/qt56-env.sh
    qtpkg: "'qt56base qt56quickcontrols qt56quickcontrols2 qt56svg mesa-common-dev libgl1-mesa-dev'"
    qtppa: ppa:beineri/opt-qt56-trusty
    deployscript: "'build/deploy.ubuntu.sh -qt'"
  ### Ubuntu 14.04 i386, Qt 5.5 - DO NOT DEPLOY
  - xdist: ubuntu
    xdistver: "14.04"
    arch: i386
    init: /sbin/init
    qtenv: /opt/qt55/bin/qt55-env.sh
    qtpkg: "'qt55base qt55quickcontrols qt55svg mesa-common-dev libgl1-mesa-dev'"
    qtppa: ppa:beineri/opt-qt551-trusty
  ### Ubuntu 14.04 i386, Qt 5.6 - DEPLOY
  - xdist: ubuntu
    xdistver: "14.04"
    arch: i386
    init: /sbin/init
    qtenv: /opt/qt56/bin/qt56-env.sh
    qtpkg: "'qt56base qt56quickcontrols qt56quickcontrols2 qt56svg mesa-common-dev libgl1-mesa-dev'"
    qtppa: ppa:beineri/opt-qt56-trusty
    deployscript: "'build/deploy.ubuntu.sh -qt'"
  ###
  ### Ubuntu 15.10
  ###
  ### Ubuntu 15.10 x86_64, Qt 5.5 - DEPLOY
  - xdist: ubuntu
    xdistver: "15.10"
    init: /sbin/init
    qtpkg: "'qtbase5-dev qtdeclarative5-dev libqt5svg5-dev qtdeclarative5-controls-plugin libqt5libqgtk2'"
    qmakeopt: "-qt5"
    qtppa: ppa:canonical-qt5-edgers/backup-qt551
    deployscript: "'build/deploy.ubuntu.sh -qt'"
  ### Ubuntu 15.10 i386, Qt 5.5 - DEPLOY
  - xdist: ubuntu
    xdistver: "15.10"
    arch: i386
    init: /sbin/init
    qtpkg: "'qtbase5-dev qtdeclarative5-dev libqt5svg5-dev qtdeclarative5-controls-plugin libqt5libqgtk2'"
    qmakeopt: "-qt5"
    qtppa: ppa:canonical-qt5-edgers/backup-qt551
    deployscript: "'build/deploy.ubuntu.sh -qt'"
  ###
  ### Ubuntu 16.04
  ###
  ### Ubuntu 16.04 x86_64, Qt 5.5 - DEPLOY
  - xdist: ubuntu
    xdistver: "16.04"
    init: /sbin/init
    qtpkg: "'qtbase5-dev qtdeclarative5-dev libqt5svg5-dev'"
    qmakeopt: "-qt5"
    deployscript: build/deploy.ubuntu.sh
  ### Ubuntu 16.04 i386, Qt 5.5 - DEPLOY
  - xdist: ubuntu
    xdistver: "16.04"
    arch: i386
    init: /sbin/init
    qtpkg: "'qtbase5-dev qtdeclarative5-dev libqt5svg5-dev'"
    qmakeopt: "-qt5"
    deployscript: build/deploy.ubuntu.sh
  ### OS X
  - xdist: osx

services:
  - docker

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ];
      docker pull ${xdist}:${xdistver};
      export CONTAINER=$(docker run --detach --privileged --volume="${PWD}":/build:rw ${xdist}:${xdistver} ${init});
      export DOCKER="docker exec --tty ${CONTAINER} env TERM=xterm";
      if [ "${xdist}" = "ubuntu" ]; then
        $DOCKER apt-get update;
        $DOCKER apt-get install -y pbuilder debootstrap devscripts;
        if [ "${arch}" = "i386" ]; then
          export ARCH="--debootstrapopts --arch --debootstrapopts i386";
          export LINUX32="linux32";
        fi;
        $DOCKER $LINUX32 pbuilder create --debootstrapopts --variant=buildd $ARCH;
      fi;
    fi

install:
  ### Install dependencies in build chroot
  # sources.list will be in Docker:/build and chroot:/root
  - if [ "${xdist}" = "ubuntu" ]; then
      $DOCKER cp /etc/apt/sources.list /build;
      touch prepare.sh;
      chmod 755 prepare.sh;
      echo "#!/bin/bash" >> prepare.sh;
      echo >> prepare.sh;
      echo "set -ex" >> prepare.sh;
      echo "cp /build/sources.list /etc/apt" >> prepare.sh;
      echo "apt-get update" >> prepare.sh;
      if [ -n "${qtppa}" ]; then
        echo "apt-get install -y software-properties-common" >> prepare.sh;
        echo "add-apt-repository -y ${qtppa}" >> prepare.sh;
      fi;
      echo "apt-get update" >> prepare.sh;
      echo "apt-get xdist-upgrade -y" >> prepare.sh;
      if [ -n "${qtpkg}" ]; then
        echo "apt-get install -y ${qtpkg}" >> prepare.sh;
      fi;
      echo "apt-get install -y lsb-release" >> prepare.sh;
      $DOCKER $LINUX32 pbuilder --execute --bindmounts "/build" --save-after-exec /build/prepare.sh;
    fi

script:
  - export USER_ID=$(id -u)
  - export GROUP_ID=$(id -g)
  - touch build.sh
  - chmod 755 build.sh
  - echo "#!/bin/bash" >> build.sh;
  - echo >> build.sh;
  - echo "set -x" >> build.sh;
  - if [ -n "${qtenv}" ]; then
      echo "source ${qtenv}" >> build.sh;
    fi
  - echo "set -ex" >> build.sh;
  - echo "cd /build" >> build.sh
  - echo "cd qtredmine" >> build.sh
  - echo "qmake ${qmakeopt} -r" >> build.sh
  - echo "make" >> build.sh
  - echo "cd .." >> build.sh
  - echo "qmake ${qmakeopt} -r" >> build.sh
  - echo "make" >> build.sh
  - echo "chown -R $USER_ID:$GROUP_ID ." >> build.sh
  - if [ "${xdist}" = "ubuntu" ]; then
      $DOCKER $LINUX32 pbuilder --execute --bindmounts "/build" /build/build.sh;
    fi

before_deploy:
  - test $TRAVIS_TEST_RESULT = 0
  - test "${deployscript}"
  ### The following commands have to define a $DEPLOYFILE
  - if [ "${xdist}" = "ubuntu" ]; then
      echo "#!/bin/bash" >> deploy.sh;
      echo "set -ex" >> deploy.sh;
      echo "cd /build" >> deploy.sh;
      echo "${deployscript} > .deployfile" >> deploy.sh;
      echo "chown -R $USER_ID:$GROUP_ID ." >> deploy.sh;
      $DOCKER $LINUX32 pbuilder --execute --bindmounts "/build" /build/deploy.sh;
      export DEPLOYFILE=$(cat .deployfile | tr -d '\r\n');
    fi

deploy:
  provider: releases
  api_key:
    secure: F3wBYR8oHwrLEJWwH6eQbTjhrNFCdklUQhjfq4wzixZO3bm5PTR/K3wvxaINmhsSoEdYHnSwzyVC3kWzcKWQX/3msCV4VyLvo1SULoz3RA2f4iY63Kbo0KzKiT+2rmOuGNHDDXCvIVKIhD81H5hR5YYhTPF7aBGfxvpb1Z2l9zfASP7fd6oZhdxolNfT3OS03AIB1on6pLgtv/aaizh5vAlVn32OwyFiJ5iOo+owFvYgImj082YTN025tVUh9KMjWD5naLgQ5ltflcWnIndjOwnasHQesmSKmCU5TBB7gAjpaRt0zKNdgDZ2RS8UFmaV5BIzF6TgP3I/IsVET5Fqqjil8PUSJZrGm/fbL+8yp9tpQ5chQcTV/ssYoQPZ0I2asZjuV6ypgSCIVuCdzcUewZgkLJglfKKTf1WqxKsjleaTZu9HpCyZ+XYp5L2Y+twsFZGgzYZoa43+/GtinNabNG75rIq0mc3cnNM/BQRvyUeAf9JUGeauQhTjJloiSKs3wl3VVYtvCiggWmKEjPYDNqgDLMaw10WMLt55f+i1VwzcBtRyZOkBC0/YVKLrM21JGOgbgEBtTam5G9+0Ysb6bwymTTD02N6tXjLFS9om2UyN1LzGzW+Sy0PW4L8RhoafwZEVTMDwxZh6Noo8JTZAN/XmOPM7cGfavVZchn2CWZc=
  file_glob: true
  file: ${DEPLOYFILE}
  skip_cleanup: true
  on:
    repo: fathomssen/redtimer
    condition: -n "${deployscript}"
    tags: true
