language: cpp
compiler: clang

env:
  global:
  - GH_REF=github.com/fathomssen/redtimer.git
  - secure: "NB/LJ6BgV9bIzHiC48jCajvDQqnp178cBx94R7bJQYqCP2Q+NbO0tV1wAn29ewaIqTaZT/E2qpuMM2uUBZAEqDva8JSXaX2yAHlp2DW4G90/ZIncDFlRqVhUxEq+dW5wL35xakMkkcZpBAfdOEvsPxmg1O071N6b02bPX/dP5QqUm1xqq73iyK+vfRlAIK7npua7nQIAwJk28eQ0OrsRNupsxZYjp1nmMouvUb6/qDc6SzJdSlqGaP+qMyOPlLkkTd2zgC59UR0P4KF7MbvGpQ+jEQ7jh9tZ4mfZbIz9rKy/5TnUs2giCpHEO+Ah1baLuDakOthdeaP57dw92NhMmZA1++2GUp1FxJ4fRsjuctyj8lXKgBVJV55GXGRzphuNQdfNwfc54CzyO4tXpAbX8IFmndJEia+FWIOD3q+N0o8UwouWhwE79U9vCDFA8SOTHtyLkMl+6QIiuQgocPpBCeJs5Jmd9W2lJL3aQoDnjsEDJAF9So9mUWCEKrTRl1szk0Yw4QIxp4WIfn79h8F8sPYtnp/7dqqlGqf2vSZ3+mlkVS4r8Me0nS5qrDRMC3JmCS5QSfO0TrJgTfW8eUn/ru3F2KpN1EngO1phM0n1SSpIdW2G6EDnHpwj2Wauw+p8RA4zRmC8GLbFBScXIW4yQPiaF/E9gFeNrajGWCbWKt0="

matrix:
  exclude:
    # Workaround to prevent building in an empty environment
    - compiler: clang
  include:
    ####################### macOS #######################
    ###
    ### macOS 10.12
    ###
    - os: osx
      osx_image: xcode8.3
      env:
        - dist: "macos"
        - distver: "10.12"
        - distname: "sierra"
    ###
    ### OS X 10.11
    ###
    - os: osx
      osx_image: xcode8
      env:
        - dist: "osx"
        - distver: "10.11"
        - distname: "el-capitan"
    ###
    ### OS X 10.10
    ###
    - os: osx
      osx_image: xcode6.4
      env:
        - dist: "osx"
        - distver: "10.10"
        - distname: "yosemite"
    ####################### Linux #######################
    - os: linux
      dist: trusty
      sudo: required
      env:
        - qtenv: /opt/qt59/bin/qt59-env.sh
        - qtpkg: "'qt59base qt59quickcontrols qt59quickcontrols2 qt59svg qt59x11extras mesa-common-dev libgl1-mesa-dev'"
        - qtppa: ppa:beineri/opt-qt591-trusty

services:
  - docker

before_install:
  ### Create aliases for checking variables
  - function run() {
      if [ "$1" = "false" ]; then
        return 0;
      fi;
      shift;
      "$@";
    }
  - export isLinux=$( [[ "$TRAVIS_OS_NAME" == "linux" ]] && echo true || echo false )
  - export isOsX=$( [[ "$TRAVIS_OS_NAME" == "osx" ]] && echo true || echo false )
  - export isMacOs=$( [[ "$isOsX" == "true" && "${distver}" > "10.11" ]] && echo true || echo false )
  ### Version names
  - if [ -n "${TRAVIS_TAG}" ]; then
      export TRAVIS_VERSION="${TRAVIS_TAG}";
      export VERSION="${TRAVIS_TAG#v}";
    fi
  - if [ -n "${TRAVIS_BRANCH}" ]; then
      export TRAVIS_VERSION="branch-${TRAVIS_BRANCH}";
      export VERSION="${TRAVIS_BRANCH}";
      if [ "${TRAVIS_BRANCH}" == "master" ]; then export VERSION="9999"; fi;
    fi
  - run $isLinux export PREFIX=redtimer-${TRAVIS_VERSION}-linux-x86_64
  - run $isOsX export PREFIX=redtimer-${TRAVIS_VERSION}-${dist}-${distver}-${distname}
  ### Linux
  - run $isLinux sudo add-apt-repository -y ${qtppa}
  - run $isLinux sudo apt-get update
  ### OS X
  - run $isOsX brew update

install:
  ### Linux
  # Install dependencies
  - run $isLinux sudo apt-get install -y --force-yes ${qtpkg}
  ### OS X
  ### Install Qt5
  - run $isOsX brew install qt5
  - run $isOsX brew linkapps qt5
  - run $isOsX brew link --force qt5

script:
  - run $isLinux source ${qtenv}
  - qmake -r
  - make

after_success:
  # Linux
  - run $isLinux sudo apt-get install -y --force-yes ruby-dev build-essential rpm
  - run $isLinux git clone https://github.com/jordansissel/fpm.git
  - run $isLinux pushd fpm
  - run $isLinux bundle install
  - run $isLinux make
  - run $isLinux sudo make install
  - run $isLinux popd
  - run $isLinux deploy/deploy.linux.sh $PREFIX $VERSION
  # OS X
  - run $isOsX deploy/deploy.osx.sh $PREFIX $VERSION
  # Both
  - export DEPLOYFILE=$PREFIX.*
  - git clone --branch gh-pages --single-branch --depth 1 https://github.com/fathomssen/redtimer.git gh-pages
  - cp -a $DEPLOYFILE gh-pages
  - pushd gh-pages
  - git config user.name "Frederick Thomssen"
  - git config user.email "thomssen@thomssen-it.de"
  - git add .
  - git commit -m "Deploy to GitHub Pages"
  - git push --quiet "https://${GH_TOKEN}@${GH_REF}" gh-pages > /dev/null 2>&1
  - popd

deploy:
  ### Upload releases
  - provider: releases
    api_key:
      secure: F3wBYR8oHwrLEJWwH6eQbTjhrNFCdklUQhjfq4wzixZO3bm5PTR/K3wvxaINmhsSoEdYHnSwzyVC3kWzcKWQX/3msCV4VyLvo1SULoz3RA2f4iY63Kbo0KzKiT+2rmOuGNHDDXCvIVKIhD81H5hR5YYhTPF7aBGfxvpb1Z2l9zfASP7fd6oZhdxolNfT3OS03AIB1on6pLgtv/aaizh5vAlVn32OwyFiJ5iOo+owFvYgImj082YTN025tVUh9KMjWD5naLgQ5ltflcWnIndjOwnasHQesmSKmCU5TBB7gAjpaRt0zKNdgDZ2RS8UFmaV5BIzF6TgP3I/IsVET5Fqqjil8PUSJZrGm/fbL+8yp9tpQ5chQcTV/ssYoQPZ0I2asZjuV6ypgSCIVuCdzcUewZgkLJglfKKTf1WqxKsjleaTZu9HpCyZ+XYp5L2Y+twsFZGgzYZoa43+/GtinNabNG75rIq0mc3cnNM/BQRvyUeAf9JUGeauQhTjJloiSKs3wl3VVYtvCiggWmKEjPYDNqgDLMaw10WMLt55f+i1VwzcBtRyZOkBC0/YVKLrM21JGOgbgEBtTam5G9+0Ysb6bwymTTD02N6tXjLFS9om2UyN1LzGzW+Sy0PW4L8RhoafwZEVTMDwxZh6Noo8JTZAN/XmOPM7cGfavVZchn2CWZc=
    file_glob: true
    file: ${DEPLOYFILE}
    skip_cleanup: true
    on:
      tags: true
