sudo: required
dist: trusty

env:
  global:
  matrix:
    ###
    ### Ubuntu 14.04
    ###
    ### Ubuntu 14.04 x86_64, Qt 5.5 - DO NOT DEPLOY
    - dist: ubuntu
      distver: "14.04"
      init: /sbin/init
      qtver: 55
      qtenv: /opt/qt55/bin/qt55-env.sh
      qtpkg: "'qt55base qt55quickcontrols qt55svg mesa-common-dev libgl1-mesa-dev'"
      qtppa: ppa:beineri/opt-qt551-trusty
    ### Ubuntu 14.04 x86_64, Qt 5.6 - DEPLOY
    - dist: ubuntu
      distver: "14.04"
      init: /sbin/init
      qtver: 56
      qtenv: /opt/qt56/bin/qt56-env.sh
      qtpkg: "'qt56base qt56quickcontrols qt56quickcontrols2 qt56svg mesa-common-dev libgl1-mesa-dev'"
      qtppa: ppa:beineri/opt-qt56-trusty
      deployscript: "'build/deploy.ubuntu.sh -qt'"
    ###
    ### Ubuntu 15.10
    ###
    ### Ubuntu 15.10 x86_64, Qt 5.5 - DO NOT DEPLOY
    - dist: ubuntu
      distver: "15.10"
      init: /sbin/init
      qtver: 55
      qtenv: /opt/qt55/bin/qt55-env.sh
      qtpkg: "'qt55base qt55quickcontrols qt55svg mesa-common-dev libgl1-mesa-dev'"
      qtppa: ppa:beineri/opt-qt551-trusty
    ### Ubuntu 15.10 x86_64, Qt 5.6 - DEPLOY
    - dist: ubuntu
      distver: "15.10"
      init: /sbin/init
      qtver: 56
      qtenv: /opt/qt56/bin/qt56-env.sh
      qtpkg: "'qt56base qt56quickcontrols qt56quickcontrols2 qt56svg mesa-common-dev libgl1-mesa-dev'"
      qtppa: ppa:beineri/opt-qt56-trusty
      deployscript: "'build/deploy.ubuntu.sh -qt'"
    ###
    ### Ubuntu 16.04
    ###
    ### Ubuntu 16.04 x86_64, Qt 5.5 - DEPLOY
    - dist: ubuntu
      distver: "16.04"
      init: /sbin/init
      qtpkg: "'qtbase5-dev qtdeclarative5-dev libqt5svg5-dev'"
      qmakeopt: "-qt5"
      deployscript: build/deploy.ubuntu.sh

services:
  - docker

before_install:
  - docker pull ${dist}:${distver}
  - export CONTAINER=$(docker run --detach --privileged --volume="${PWD}":/build:rw ${dist}:${distver} ${init})
  - export DOCKER="docker exec --tty ${CONTAINER} env TERM=xterm"
  ### Prepare build chroot
  - if [ "${dist}" = "ubuntu" ]; then
      $DOCKER apt-get update;
      $DOCKER apt-get install -y pbuilder debootstrap devscripts;
      echo -n "deb http://archive.ubuntu.com/ubuntu/ trusty main restricted" >> othermirror;
      echo -n "|" >> othermirror;
      echo -n "deb http://archive.ubuntu.com/ubuntu/ trusty universe" >> othermirror;
      echo -n "|" >> othermirror;
      echo -n "deb http://archive.ubuntu.com/ubuntu/ trusty multiverse" >> othermirror;
      echo -n "|" >> othermirror;
      echo -n "deb http://archive.ubuntu.com/ubuntu/ trusty-updates main restricted" >> othermirror;
      echo -n "|" >> othermirror;
      echo -n "deb http://archive.ubuntu.com/ubuntu/ trusty-updates universe" >> othermirror;
      echo -n "|" >> othermirror;
      echo -n "deb http://archive.ubuntu.com/ubuntu/ trusty-updates multiverse" >> othermirror;
      echo -n "|" >> othermirror;
      echo -n "deb http://security.ubuntu.com/ubuntu trusty-security main restricted" >> othermirror;
      echo -n "|" >> othermirror;
      echo -n "deb http://security.ubuntu.com/ubuntu trusty-security universe" >> othermirror;
      echo -n "|" >> othermirror;
      echo -n "deb http://security.ubuntu.com/ubuntu trusty-security multiverse" >> othermirror;
      $DOCKER pbuilder create --debootstrapopts --variant=buildd --othermirror="\"$(cat othermirror)\"";
    fi

install:
  ### Install dependencies in build chroot
  - if [ "${dist}" = "ubuntu" ]; then
      touch prepare;
      chmod 755 prepare;
      if [ -n "${qtppa}" ]; then
        echo "apt-get update" >> prepare;
        echo "apt-get install -y software-properties-common" >> prepare;
        echo "add-apt-repository -y ${qtppa}" >> prepare;
      fi;
      echo "apt-get update" >> prepare;
      if [ -n "${qtpkg}" ]; then
        echo "apt-get install -y ${qtpkg}" >> prepare;
      fi;
      $DOCKER pbuilder --execute --save-after-exec prepare
    fi

script:
  - export USER_ID=$(id -u)
  - export GROUP_ID=$(id -g)
  - if [ -n "${qtenv}" ]; then
      export SCRIPT="source ${qtenv};";
    fi
  - export SCRIPT="$SCRIPT
      cd /build;
      cd qtredmine;
      qmake ${qmakeopt} -r;
      make -j2;
      cd ..;
      qmake ${qmakeopt} -r;
      make -j2;
      chown -R $USER_ID:$GROUP_ID ."
  - if [ "${dist}" = "ubuntu" ]; then
      echo "$SCRIPT" > build;
      $DOCKER pbuilder --bindmounts="/build" --execute --save-after-exec build;
    fi

before_deploy:
  - test $TRAVIS_TEST_RESULT = 0
  - test "${deployscript}"
  - $DOCKER bash -c "cd /build; ${deployscript}; chown -R $USER_ID:$GROUP_ID ." > .deployfile
  - export DEPLOYFILE=$(cat .deployfile | tr -d '\r\n')

deploy:
  provider: releases
  api_key:
    secure: F3wBYR8oHwrLEJWwH6eQbTjhrNFCdklUQhjfq4wzixZO3bm5PTR/K3wvxaINmhsSoEdYHnSwzyVC3kWzcKWQX/3msCV4VyLvo1SULoz3RA2f4iY63Kbo0KzKiT+2rmOuGNHDDXCvIVKIhD81H5hR5YYhTPF7aBGfxvpb1Z2l9zfASP7fd6oZhdxolNfT3OS03AIB1on6pLgtv/aaizh5vAlVn32OwyFiJ5iOo+owFvYgImj082YTN025tVUh9KMjWD5naLgQ5ltflcWnIndjOwnasHQesmSKmCU5TBB7gAjpaRt0zKNdgDZ2RS8UFmaV5BIzF6TgP3I/IsVET5Fqqjil8PUSJZrGm/fbL+8yp9tpQ5chQcTV/ssYoQPZ0I2asZjuV6ypgSCIVuCdzcUewZgkLJglfKKTf1WqxKsjleaTZu9HpCyZ+XYp5L2Y+twsFZGgzYZoa43+/GtinNabNG75rIq0mc3cnNM/BQRvyUeAf9JUGeauQhTjJloiSKs3wl3VVYtvCiggWmKEjPYDNqgDLMaw10WMLt55f+i1VwzcBtRyZOkBC0/YVKLrM21JGOgbgEBtTam5G9+0Ysb6bwymTTD02N6tXjLFS9om2UyN1LzGzW+Sy0PW4L8RhoafwZEVTMDwxZh6Noo8JTZAN/XmOPM7cGfavVZchn2CWZc=
  file_glob: true
  file: ${DEPLOYFILE}
  skip_cleanup: true
  on:
    repo: fathomssen/redtimer
    condition: -n "${deployscript}"
    tags: true
